"""
Speech-to-Text providers
~~~~~~~~~~~~~~~~~~~~~~~~~~~

A small abstraction layer so subtitles can be generated by more than one STT
engine while the rest of the app stays exactly the same.

Every provider implements the SAME contract:

    async def transcribe(video_path, video_clip=None) -> List[Tuple[float, str]]

and returns a list of ``(start_time_seconds, word)`` tuples -- the format that
``DeepSub.render_subtitles`` already expects. The renderer never needs to know
which engine produced the words.

Currently supported (set ``CONFIG["STT_PROVIDER"]`` in conf.py):
    * "deepgram" -> Deepgram pre-recorded transcription
    * "60db"     -> 60db /stt endpoint
"""

import os
import tempfile
from typing import List, Optional, Tuple

import httpx
from deepgram import Deepgram
from rich import print

from conf import CONFIG, DEEPGRAM_KEY, SIXTYDB_KEY

# A single subtitle token: (start_time_in_seconds, word_text)
Subtitle = Tuple[float, str]


class STTProvider:
    """Base class describing the common transcription interface."""

    # Human-readable name, also used in log messages.
    name: str = "base"

    async def transcribe(
        self, video_path: os.PathLike, video_clip=None
    ) -> List[Subtitle]:
        """Transcribe ``video_path`` and return ``[(start, word), ...]``.

        :param video_path: Path to the source video file.
        :param video_clip: Optional already-loaded moviepy clip. Providers that
            need the audio track can reuse it instead of re-reading the file.
        """
        raise NotImplementedError


class DeepgramProvider(STTProvider):
    """Transcribe using Deepgram's pre-recorded API (the original engine)."""

    name = "deepgram"

    async def transcribe(
        self, video_path: os.PathLike, video_clip=None
    ) -> List[Subtitle]:
        if not DEEPGRAM_KEY:
            raise RuntimeError(
                "DEEPGRAM_KEY is not set. Add it to your .env file."
            )

        dg_client = Deepgram(DEEPGRAM_KEY)

        # Deepgram extracts the audio itself, so the whole video can be sent.
        with open(video_path, "rb") as f:
            video_data = f.read()

        source = {"buffer": video_data, "mimetype": "video/mp4"}
        options = {"punctuate": True, "language": CONFIG["STT_LANGUAGE"]}

        response = await dg_client.transcription.prerecorded(source, options)

        words = response["results"]["channels"][0]["alternatives"][0]["words"]
        return [(round(float(w["start"]), 3), w["word"]) for w in words]


class SixtyDBProvider(STTProvider):
    """Transcribe using the 60db /stt endpoint.

    60db expects an audio file (multipart upload, max 10 MB). We extract a
    compressed mp3 audio track from the video with moviepy before uploading,
    which keeps the request small and avoids the video-size limit.
    """

    name = "60db"
    BASE_URL = "https://api.60db.ai"

    async def transcribe(
        self, video_path: os.PathLike, video_clip=None
    ) -> List[Subtitle]:
        if not SIXTYDB_KEY:
            raise RuntimeError(
                "SIXTYDB_KEY is not set. Add it to your .env file."
            )

        audio_path = self._extract_audio(video_path, video_clip)
        try:
            with open(audio_path, "rb") as f:
                audio_bytes = f.read()

            headers = {"Authorization": f"Bearer {SIXTYDB_KEY}"}
            # 60db uses ISO 639-1 codes (e.g. "en"), so strip any region suffix.
            language = CONFIG["STT_LANGUAGE"].split("-")[0]
            data = {
                "return_timestamps": "word",  # we need per-word start times
                "language": language,
            }
            files = {
                "file": (os.path.basename(audio_path), audio_bytes, "audio/mpeg")
            }

            async with httpx.AsyncClient(timeout=600.0) as client:
                resp = await client.post(
                    f"{self.BASE_URL}/stt",
                    headers=headers,
                    data=data,
                    files=files,
                )
            resp.raise_for_status()
            payload = resp.json()

            words = payload.get("words") or []
            if not words:
                print(
                    "[bold yellow]Warning:[/bold yellow] 60db returned no "
                    "word-level timestamps. Was there speech in the audio?"
                )

            subtitles: List[Subtitle] = []
            for w in words:
                start = self._word_start(w)
                text = self._word_text(w)
                if start is None or not text:
                    continue
                subtitles.append((round(float(start), 3), text))
            return subtitles
        finally:
            # Only delete files we created ourselves.
            if audio_path.endswith(self._TEMP_SUFFIX) and os.path.exists(audio_path):
                os.remove(audio_path)

    # --- helpers -----------------------------------------------------------

    _TEMP_SUFFIX = ".deepsub.mp3"

    def _extract_audio(self, video_path, video_clip) -> str:
        """Write the video's audio track to a temp mp3 and return its path."""
        import moviepy.editor as mp  # local import: only 60db needs this here

        # Reuse the loaded clip if it already has an audio track; otherwise
        # reopen the file forcing audio on (the main clip may be audio=False).
        if video_clip is not None and video_clip.audio is not None:
            clip = video_clip
            opened_here = False
        else:
            clip = mp.VideoFileClip(str(video_path))
            opened_here = True

        try:
            if clip.audio is None:
                raise RuntimeError(
                    "The video has no audio track, so it cannot be transcribed."
                )
            tmp_path = os.path.join(
                tempfile.gettempdir(), "60db_input" + self._TEMP_SUFFIX
            )
            clip.audio.write_audiofile(tmp_path, logger=None)
            return tmp_path
        finally:
            if opened_here:
                clip.close()

    @staticmethod
    def _word_start(w: dict) -> Optional[float]:
        """Pull the start time from a 60db word object, tolerant of key names."""
        for key in ("start", "start_time", "startTime"):
            if w.get(key) is not None:
                return w[key]
        return None

    @staticmethod
    def _word_text(w: dict) -> str:
        """Pull the word text from a 60db word object, tolerant of key names."""
        for key in ("word", "text", "punctuated_word"):
            if w.get(key):
                return w[key]
        return ""


# Registry of available providers, keyed by the value used in conf.py.
PROVIDERS = {
    DeepgramProvider.name: DeepgramProvider,
    SixtyDBProvider.name: SixtyDBProvider,
}


def get_provider(name: Optional[str] = None) -> STTProvider:
    """Return an instance of the configured STT provider.

    :param name: Override the provider; defaults to ``CONFIG["STT_PROVIDER"]``.
    """
    name = (name or CONFIG.get("STT_PROVIDER", "deepgram")).lower()
    if name not in PROVIDERS:
        raise ValueError(
            f"Unknown STT_PROVIDER '{name}'. "
            f"Choose one of: {', '.join(PROVIDERS)}."
        )
    return PROVIDERS[name]()
